### ISSUE TITLE
App sends user's OpenAPI key to Anse?

### ISSUE THREAD

**Issue by LoopControl** [anse-app/anse#55]
### What operating system are you using?

Doesn't matter

### What browser are you using?

Doesn't matter

### Describe the bug

When using https://anse.app/ and using my own OpenAPI key, I'm noticing that your app is making a request to https://anse.app/api/handle/provider-openai and it contains my API key in the body of the summarize request.

I can understand doing that when the "Use Backend" option is on but when it's off, you really should not be sending my API key anywhere.

### What provider are you using?

OpenAI

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
Hi, thanks for the find!

Our logic is that the default is to request OpenAI directly; when "Use Backend" option is checked, the requests are forwarded through our interface (but they are safe, reference [api/handle/[provider].ts](https://github.com/anse-app/anse/blob/main/src/pages/api/handle/%5Bprovider%5D.ts))

However, we have a bug where the option may be turned on but shown as unchecked (because of a bug in getting local setting items). You can try to re-check it and turn it off.

**Comment by LoopControl** [comment]
Here's a screenshot I took of the network when this is happening. As you can see, all the actual inference requests are going to my local (http://127.0.0.1) -- so it's clearly not using the "Backend option".

However even then you can see that the requests to summarize are going to anse.app domain (and returning 500s too). 

![Screenshot from 2023-06-02 19-52-44](https://github.com/anse-app/anse/assets/14502039/2e0f9587-7fb5-442e-bb7a-15dede1e7c1c)

**Comment by ddiu8081** [comment]
> so it's clearly not using the "Backend option".

Can you help me to check the IndexedDB storage of the browser? The settings items are stored under `settings-keyval` database, then check the value of `requestWithBackend` option. I need to confirm if this is caused by the bug I mentioned above.

![ScreenShot 2023-06-03 at 11 13 23@2x](https://github.com/anse-app/anse/assets/1998168/4e49590d-3289-4d01-9ca9-0d3018f191f0)

**Comment by LoopControl** [comment]
Sure, here's a screenshot I just took of the indexDB settings (`requestWithBackend` is `false`):

![Screenshot from 2023-06-03 02-11-10](https://github.com/anse-app/anse/assets/14502039/c9737ebc-1f44-4166-b8ca-cca9b88e33b0)

**Comment by ddiu8081** [comment]
I got it. The request used to summarize the conversation title seems to have incorrectly ignored this setting item. I'll fix it later.

**Comment by ddiu8081** [comment]
fixed in https://github.com/anse-app/anse/commit/924393bc517ea1e0c58af6c5fa1deeaba32a1f69, you can try it again, thanks!

**Comment by LoopControl** [comment]
Works great now!

![Screenshot from 2023-06-04 19-00-05](https://github.com/anse-app/anse/assets/14502039/5c43f081-241e-4d0e-a880-4a1c9bbce7dd)

Thanks for the quick fix @ddiu8081
